use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[macro_export]
macro_rules! log {
    ($($arg:tt)*) => {{
        let message = format!($($arg)*);
        println!("cargo:warning={}", message);
    }};
}

fn dump_env() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
    let target_dir = env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| {
        let default = Path::new(&manifest_dir).join("target");
        default.to_str().unwrap().to_owned()
    });
    println!("cargo:rustc-env=PROJECT_ROOT={}/", manifest_dir);
    println!("cargo:rustc-env=TARGET_DIR={}/", target_dir);
}

fn project_root() -> PathBuf {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"))
}

fn generate_gui_adjustables() {
    let root = project_root();
    let config_path = root.join("config").join("gui.toml");

    let content = match fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(e) => {
            log!(
                "skipping GUI codegen: failed to read {}: {}",
                config_path.display(),
                e
            );
            return;
        }
    };

    let parsed: toml::Value = match content.parse() {
        Ok(v) => v,
        Err(e) => {
            log!(
                "skipping GUI codegen: failed to parse {}: {}",
                config_path.display(),
                e
            );
            return;
        }
    };

    let schema_version = parsed
        .get("schema_version")
        .and_then(|v| v.as_integer())
        .unwrap_or(0);

    let mut descriptors = Vec::new();

    if let Some(sections) = parsed.get("section").and_then(|v| v.as_array()) {
        for section in sections {
            let table = match section.as_table() {
                Some(t) => t,
                None => continue,
            };

            let section_name = match table.get("name").and_then(|v| v.as_str()) {
                Some(name) => name.to_owned(),
                None => {
                    log!("GUI config generation: section without name, skipping");
                    continue;
                }
            };

            if let Some(params) = table.get("param").and_then(|v| v.as_array()) {
                for param in params {
                    let param_tbl = match param.as_table() {
                        Some(t) => t,
                        None => continue,
                    };

                    let id = match param_tbl.get("id").and_then(|v| v.as_str()) {
                        Some(id) => id.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param without id in section '{}', skipping",
                                section_name
                            );
                            continue;
                        }
                    };

                    let kind = match param_tbl.get("kind").and_then(|v| v.as_str()) {
                        Some(kind) => kind.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param '{}' in section '{}' missing kind, skipping",
                                id, section_name
                            );
                            continue;
                        }
                    };

                    let label = match param_tbl.get("label").and_then(|v| v.as_str()) {
                        Some(label) => label.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param '{}' in section '{}' missing label, skipping",
                                id, section_name
                            );
                            continue;
                        }
                    };

                    descriptors.push((section_name.clone(), id, kind, label));
                }
            }
        }
    }

    let generated_dir = root.join("src").join("app").join("generated");
    if let Err(e) = fs::create_dir_all(&generated_dir) {
        log!(
            "skipping GUI codegen: failed to create {}: {}",
            generated_dir.display(),
            e
        );
        return;
    }

    let out_path = generated_dir.join("gui_adjustables_gen.rs");

    let mut code = String::new();
    code.push_str("// @generated by build.rs - do not edit.\n");
    code.push_str("// This file reflects config/gui.toml at build time.\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub const GENERATED_SCHEMA_VERSION: u32 = ");
    code.push_str(&schema_version.to_string());
    code.push_str(";\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub struct GeneratedGuiParamDescriptor {\n");
    code.push_str("    pub section: &'static str,\n");
    code.push_str("    pub id: &'static str,\n");
    code.push_str("    pub kind: &'static str,\n");
    code.push_str("    pub label: &'static str,\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub static GENERATED_GUI_PARAMS: &[GeneratedGuiParamDescriptor] = &[\n");

    for (section, id, kind, label) in descriptors {
        code.push_str("    GeneratedGuiParamDescriptor {\n");
        code.push_str(&format!(
            "        section: \"{}\",\n",
            section.replace('"', "\\\"")
        ));
        code.push_str(&format!("        id: \"{}\",\n", id.replace('"', "\\\"")));
        code.push_str(&format!(
            "        kind: \"{}\",\n",
            kind.replace('"', "\\\"")
        ));
        code.push_str(&format!(
            "        label: \"{}\",\n",
            label.replace('"', "\\\"")
        ));
        code.push_str("    },\n");
    }

    code.push_str("];\n");

    if let Err(e) = fs::write(&out_path, code) {
        log!(
            "failed to write generated GUI code to {}: {}",
            out_path.display(),
            e
        );
    } else {
        log!("wrote generated GUI descriptors to {}", out_path.display());
    }
}

fn main() {
    dump_env();
    generate_gui_adjustables();
}
