use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[macro_export]
macro_rules! log {
    ($($arg:tt)*) => {{
        let message = format!($($arg)*);
        println!("cargo:warning={}", message);
    }};
}

fn dump_env() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set");
    let target_dir = env::var("CARGO_TARGET_DIR").unwrap_or_else(|_| {
        let default = Path::new(&manifest_dir).join("target");
        default.to_str().unwrap().to_owned()
    });
    println!("cargo:rustc-env=PROJECT_ROOT={}/", manifest_dir);
    println!("cargo:rustc-env=TARGET_DIR={}/", target_dir);
}

fn project_root() -> PathBuf {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"))
}

fn generate_gui_adjustables() {
    let root = project_root();
    let config_path = root.join("config").join("gui.toml");

    let content = match fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(e) => {
            log!(
                "skipping GUI codegen: failed to read {}: {}",
                config_path.display(),
                e
            );
            return;
        }
    };

    let parsed: toml::Value = match content.parse() {
        Ok(v) => v,
        Err(e) => {
            log!(
                "skipping GUI codegen: failed to parse {}: {}",
                config_path.display(),
                e
            );
            return;
        }
    };

    let schema_version = parsed
        .get("schema_version")
        .and_then(|v| v.as_integer())
        .unwrap_or(0);

    let mut descriptors: Vec<(String, String, String, String)> = Vec::new();

    if let Some(sections) = parsed.get("section").and_then(|v| v.as_array()) {
        for section in sections {
            let table = match section.as_table() {
                Some(t) => t,
                None => continue,
            };

            let section_name = match table.get("name").and_then(|v| v.as_str()) {
                Some(name) => name.to_owned(),
                None => {
                    log!("GUI config generation: section without name, skipping");
                    continue;
                }
            };

            if let Some(params) = table.get("param").and_then(|v| v.as_array()) {
                for param in params {
                    let param_tbl = match param.as_table() {
                        Some(t) => t,
                        None => continue,
                    };

                    let id = match param_tbl.get("id").and_then(|v| v.as_str()) {
                        Some(id) => id.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param without id in section '{}', skipping",
                                section_name
                            );
                            continue;
                        }
                    };

                    let kind = match param_tbl.get("kind").and_then(|v| v.as_str()) {
                        Some(kind) => kind.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param '{}' in section '{}' missing kind, skipping",
                                id, section_name
                            );
                            continue;
                        }
                    };

                    let label = match param_tbl.get("label").and_then(|v| v.as_str()) {
                        Some(label) => label.to_owned(),
                        None => {
                            log!(
                                "GUI config generation: param '{}' in section '{}' missing label, skipping",
                                id, section_name
                            );
                            continue;
                        }
                    };

                    descriptors.push((section_name.clone(), id, kind, label));
                }
            }
        }
    }

    let generated_dir = root.join("src").join("app").join("generated");
    if let Err(e) = fs::create_dir_all(&generated_dir) {
        log!(
            "skipping GUI codegen: failed to create {}: {}",
            generated_dir.display(),
            e
        );
        return;
    }

    let out_path = generated_dir.join("gui_adjustables_gen.rs");

    let mut code = String::new();
    code.push_str("// @generated by build.rs - do not edit.\n");
    code.push_str("// This file reflects config/gui.toml at build time.\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub const GENERATED_SCHEMA_VERSION: u32 = ");
    code.push_str(&schema_version.to_string());
    code.push_str(";\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub struct GeneratedGuiParamDescriptor {\n");
    code.push_str("    pub section: &'static str,\n");
    code.push_str("    pub id: &'static str,\n");
    code.push_str("    pub kind: &'static str,\n");
    code.push_str("    pub label: &'static str,\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub static GENERATED_GUI_PARAMS: &[GeneratedGuiParamDescriptor] = &[\n");

    for (section, id, kind, label) in &descriptors {
        code.push_str("    GeneratedGuiParamDescriptor {\n");
        code.push_str(&format!(
            "        section: \"{}\",\n",
            section.replace('"', "\\\"")
        ));
        code.push_str(&format!("        id: \"{}\",\n", id.replace('"', "\\\"")));
        code.push_str(&format!(
            "        kind: \"{}\",\n",
            kind.replace('"', "\\\"")
        ));
        code.push_str(&format!(
            "        label: \"{}\",\n",
            label.replace('"', "\\\"")
        ));
        code.push_str("    },\n");
    }

    code.push_str("];\n\n");

    // generated struct with one field per GUI param
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub struct GeneratedGuiAdjustables {\n");
    for (_section, id, kind, _label) in &descriptors {
        let ty = match kind.as_str() {
            "float" => "crate::gui_adjustables::FloatParam",
            "int" => "crate::gui_adjustables::IntParam",
            "uint" => "crate::gui_adjustables::UintParam",
            "bool" => "crate::gui_adjustables::BoolParam",
            "color" => "crate::gui_adjustables::ColorParam",
            other => {
                log!(
                    "GUI config generation: unsupported kind '{}' for id '{}', skipping field",
                    other,
                    id
                );
                continue;
            }
        };

        code.push_str(&format!("    pub {}: {},\n", id, ty));
    }
    code.push_str("}\n\n");

    // Default implementation that loads the config file
    code.push_str("impl Default for GeneratedGuiAdjustables {\n");
    code.push_str("    fn default() -> Self {\n");
    code.push_str("        let config = crate::app::gui_config_loader::GuiConfigLoader::load();\n");
    code.push_str("        Self::from_config(&config)\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // from_config constructor that materializes params from GuiConfigFile
    code.push_str("impl GeneratedGuiAdjustables {\n");
    code.push_str(
        "    pub fn from_config(config: &crate::app::gui_config_model::GuiConfigFile) -> Self {\n",
    );
    code.push_str("        use crate::app::gui_config_model::{GuiParamKind, GuiParamValue};\n\n");

    // one local Option per field
    for (_section, id, kind, _label) in &descriptors {
        let ty = match kind.as_str() {
            "float" => "crate::gui_adjustables::FloatParam",
            "int" => "crate::gui_adjustables::IntParam",
            "uint" => "crate::gui_adjustables::UintParam",
            "bool" => "crate::gui_adjustables::BoolParam",
            "color" => "crate::gui_adjustables::ColorParam",
            _ => continue,
        };
        code.push_str(&format!(
            "        let mut {id}_field: Option<{ty}> = None;\n",
            id = id,
            ty = ty
        ));
    }

    code.push_str("\n        for section in &config.section {\n");
    code.push_str("            for param in &section.param {\n");
    code.push_str("                match param.id.as_str() {\n");

    for (_section, id, kind, _label) in &descriptors {
        code.push_str(&format!("                    \"{}\" => {{\n", id));
        match kind.as_str() {
            "float" => {
                code.push_str(
                    "                        if let (GuiParamKind::Float, GuiParamValue::Float { value, min, max }) = (&param.kind, &param.value) {\n",
                );
                code.push_str(
                    "                            let min = min.unwrap_or(0.0);\n                            let max = max.unwrap_or(1.0);\n",
                );
                code.push_str(&format!(
                    "                            {id}_field = Some(crate::gui_adjustables::FloatParam::new(*value, min..=max));\n",
                    id = id
                ));
                code.push_str("                        }\n");
            }
            "int" => {
                code.push_str(
                    "                        if let (GuiParamKind::Int, GuiParamValue::Int { value, min, max }) = (&param.kind, &param.value) {\n",
                );
                code.push_str(
                    "                            let min = min.unwrap_or(0);\n                            let max = max.unwrap_or(100);\n",
                );
                code.push_str(&format!(
                    "                            {id}_field = Some(crate::gui_adjustables::IntParam::new(*value, min..=max));\n",
                    id = id
                ));
                code.push_str("                        }\n");
            }
            "uint" => {
                code.push_str(
                    "                        if let (GuiParamKind::Uint, GuiParamValue::Uint { value, min, max }) = (&param.kind, &param.value) {\n",
                );
                code.push_str(
                    "                            let min = min.unwrap_or(0);\n                            let max = max.unwrap_or(100);\n",
                );
                code.push_str(&format!(
                    "                            {id}_field = Some(crate::gui_adjustables::UintParam::new(*value, min..=max));\n",
                    id = id
                ));
                code.push_str("                        }\n");
            }
            "bool" => {
                code.push_str(
                    "                        if let (GuiParamKind::Bool, GuiParamValue::Bool { value }) = (&param.kind, &param.value) {\n",
                );
                code.push_str(&format!(
                    "                            {id}_field = Some(crate::gui_adjustables::BoolParam::new(*value));\n",
                    id = id
                ));
                code.push_str("                        }\n");
            }
            "color" => {
                code.push_str(
                    "                        if let (GuiParamKind::Color, GuiParamValue::Color { value }) = (&param.kind, &param.value) {\n",
                );
                code.push_str(&format!(
                    "                            {id}_field = Some(crate::gui_adjustables::ColorParam::new(crate::app::gui_config::parse_color(value)));\n",
                    id = id
                ));
                code.push_str("                        }\n");
            }
            _ => {}
        }
        code.push_str("                    }\n");
    }

    code.push_str("                    _ => {}\n");
    code.push_str("                }\n");
    code.push_str("            }\n");
    code.push_str("        }\n\n");

    code.push_str("        GeneratedGuiAdjustables {\n");
    for (_section, id, kind, _label) in &descriptors {
        let expects_field = matches!(kind.as_str(), "float" | "int" | "uint" | "bool" | "color");
        if !expects_field {
            continue;
        }
        code.push_str(&format!(
            "            {id}: {id}_field.expect(\"Missing parameter: {id}\"),\n",
            id = id
        ));
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // generated accessors operating on GuiAdjustables by id
    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_float_param<'a>(adjustables: &'a crate::app::GuiAdjustables, id: &str) -> Option<&'a crate::gui_adjustables::FloatParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "float" {
            code.push_str(&format!(
                "        \"{}\" => Some(&adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_int_param<'a>(adjustables: &'a crate::app::GuiAdjustables, id: &str) -> Option<&'a crate::gui_adjustables::IntParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "int" {
            code.push_str(&format!(
                "        \"{}\" => Some(&adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_uint_param<'a>(adjustables: &'a crate::app::GuiAdjustables, id: &str) -> Option<&'a crate::gui_adjustables::UintParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "uint" {
            code.push_str(&format!(
                "        \"{}\" => Some(&adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_bool_param<'a>(adjustables: &'a crate::app::GuiAdjustables, id: &str) -> Option<&'a crate::gui_adjustables::BoolParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "bool" {
            code.push_str(&format!(
                "        \"{}\" => Some(&adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_color_param<'a>(adjustables: &'a crate::app::GuiAdjustables, id: &str) -> Option<&'a crate::gui_adjustables::ColorParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "color" {
            code.push_str(&format!(
                "        \"{}\" => Some(&adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_float_param_mut<'a>(adjustables: &'a mut crate::app::GuiAdjustables, id: &str) -> Option<&'a mut crate::gui_adjustables::FloatParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "float" {
            code.push_str(&format!(
                "        \"{}\" => Some(&mut adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_int_param_mut<'a>(adjustables: &'a mut crate::app::GuiAdjustables, id: &str) -> Option<&'a mut crate::gui_adjustables::IntParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "int" {
            code.push_str(&format!(
                "        \"{}\" => Some(&mut adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_uint_param_mut<'a>(adjustables: &'a mut crate::app::GuiAdjustables, id: &str) -> Option<&'a mut crate::gui_adjustables::UintParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "uint" {
            code.push_str(&format!(
                "        \"{}\" => Some(&mut adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_bool_param_mut<'a>(adjustables: &'a mut crate::app::GuiAdjustables, id: &str) -> Option<&'a mut crate::gui_adjustables::BoolParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "bool" {
            code.push_str(&format!(
                "        \"{}\" => Some(&mut adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("#[allow(dead_code)]\n");
    code.push_str(
        "pub fn get_color_param_mut<'a>(adjustables: &'a mut crate::app::GuiAdjustables, id: &str) -> Option<&'a mut crate::gui_adjustables::ColorParam> {\n",
    );
    code.push_str("    match id {\n");
    for (_section, id, kind, _label) in &descriptors {
        if kind == "color" {
            code.push_str(&format!(
                "        \"{}\" => Some(&mut adjustables.{}),\n",
                id, id
            ));
        }
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    if let Err(e) = fs::write(&out_path, code) {
        log!(
            "failed to write generated GUI code to {}: {}",
            out_path.display(),
            e
        );
    } else {
        log!("wrote generated GUI descriptors to {}", out_path.display());
    }
}

fn main() {
    dump_env();
    generate_gui_adjustables();
}
